/* eslint-disable import/prefer-default-export */
// eslint-disable-next-line global-require
export const APP_NAME = "Police - Central Zone";

//snackbar
export const SOMETHING_WENT_WRONG = "Something went wrong! Please try again";
export const NOT_FOUND_MESSSGE = "Not Found";
export const DUPLICATE_MESSAGE = "Duplicate value! Please try some other";
export const UNAUTHORIZED_MESSAGE = "Authentication Failure";
export const INVALID_DATA_MESSAGE = "Invalid data";
export const TURN_ON_INTERNET = "Please turn on your internet";
export const CHECK_INTERNET = "Please check your network connection";
export const NO_ENTER_MOBILE = "Please enter mobile number";
export const NO_PASSWORD = "Please enter password";
export const INVALID_MOBILE_NO = "Please enter valid mobile number";
export const INVALID_MOBILE_NO_PASSWORD = "Login failed. Invalid mobile number/password";
export const BACKPRESS_AGAIN = "Press back again to exit the app!";
export const CHECKED_IN_SUCCESSFULLY = "Checked in successfully";
export const CHECKED_IN_FAILED = "Couldn't checkin, Please try again";
export const GET_LOCATION_FAILED = "Couldn't access the app without location";
export const MANDATORY_FIELDS = "Please enter mandatory fields";
export const REGISTER_SUCCESS = "Your account created successfully";
export const PROFILE_UPDATE = "Profile updated successfully";
export const REQUEST_CREATED = "Request created successfully";

//code push
export const DOWNLOADING_PACKAGE = "Downloading Package";
export const INSTALLING_PACKAGE = "Installing Package";
export const UPDATING = "Updating";
export const SHARE_REQUEST_TEXT = `Hi, join me in assisting the ##category## to -`;
export const SHARE_URL = "https://bit.ly/ReachMeAndroid";
export const SHARE_REQUEST_TITLE = `Share Request`;
export const SHARE_REQUEST_SUBJECT = `ReachMe Request`;
export const QR_DOWNLOAD_URL = "https://police.vertace.net/user/";

//labels
export const EN = {
    SETTINGS: "SETTINGS",
    HOME: "HOME",
    FEEDBACK: "FEEDBACK",
    FEEDBACKS: "FEEDBACK LIST",
    REACHME: "REACHME",
    LANGUAGE: "Language",
    TITLE: "Title",
    DISCRIPTION: "Description",
    PHOTO: "Photo",
    SEND: "SEND",
    EBEAT: "eBeat",
    SCAN: "SCAN",
    SCAN_QR_CODE: "Scan the QR Code",
    DETAILS: "DETAILS",
    CHECKIN: "CHECK-IN",
    ACTIVATE: "ACTIVATE",
    PROFILE: "Profile",
    LOGOUT: "Logout",
    REQUESTDETAILS: "REQUEST DETAILS",
    REQUESTNO: "Request number",
    TIME: "Time",
    REQUESTOR: "Requestor",
    REQUIREMENT: "Requirement",
    STATUS: "Status",
    VOLUNTEERSCOUNT: "Volunteers Count",
    VOLUNTEERS: "Volunteers",
    VIEW: "View",
    REQUEST_TAKEN_VOLUNTEEERS: "REQUEST TAKEN VOLUNTEEERS",
    ADD_REQUEST: "ADD REQUEST",
    DATE: "Date",
    TEQUEST_TYPE: "Request Type",
    ADD: "ADD",
    CANCEL: "CANCEL",
    OK: "OK",
    WANT_TO_LOGOUT: "Are you sure you want to logout?",
    FEEDBACK_TYPE: "Feedback type",
    LOCATION_NOT_ACTIVATED: "This location is not activated yet",
    YOU_ARE_IN_LOCATION: "You are in location",
    YOU_ARE: "You are",
    AWAY_FROM_LOCATION: "meters away from location",
    SEND_FEEDBACK_TO: "Send Feedback To",
    FEEDBACK_TYPES: "Feedback Types",
    TAKE_ACTIONS: "TAKE ACTION",
    ACTIONS: "Actions",
    CONFIRMATION: "Confirmation",
    ARE_YOU_SURE_TAKE_ACTION: "Are you sure you want to Take action on this feedback",
    SEND_FEEDBACK_TO_OFFICE: "Are you sure you want to send this feedback to",
    ASSIGN_CONFIRMATION: "Are you sure you want to assign this officer",
    SELECT: "Select",
    TYPE_HERE: "Type here",
    OFFICE: "",
    FILTERS: "FILTERS",
    LANGUAGES: "Languages",
    WELFAREREQUEST: "WELFARE REQUEST",
    PERSONLIST: "PERSON LIST",
    REMARKS: "Remarks",
    NAME: "Name",
    AGE: "Age",
    GENDER: "Gender",
    CONTACTNUMBER1: "Contact Number 1",
    CONTACTNUMBER2: "Contact Number 2",
    ADDRESS: "Address",
    REQUESTTYPE: "Request Type",
    OFFICER_DIRECTORY: "OFFICER DIRECTORY",
    REQUEST_DETAILS: "REQUEST DETAILS",
    ASSIGNED_TO: "Assigned To",
    ASSIGN_TO: "ASSIGN TO",
    ASSIGNED_DATE: "Assigned Date",
    FORWARD: "Forward",
    REMOVE: "Remove",
    HISTORY: "History",
    TAKE_ACTIONS_LABEL: "Take Action",
    ACTION_LOG: "ACTIONS LOG",
    REMARKS_LOG: "REMARKS LOG",
    OFFICERS: "OFFICERS",
    OFFICER: "OFFICER",
    LOCATION_LABLE: "Location",
    LOCATIONS: "LOCATIONS",
    LOCATION: "LOCATION",
    ADD_LOCATION: "ADD LOCATION",
    LOCATION_TYPE: "Location Type",
    ACTIVATED_ON: "Activated On",
    QR_CODE: "QR Code",
    DOWNLOAD: "Download",
    CHECKIN_HISTORY: "CHECK-IN HISTORY",
    DEPARTMENT: "Department",
    CREATESUBTYPE: "CREATE SUBTYPE",
    DESCRIPTION: "Description",
    CREATEPERSON: "CREATE PERSON",
    SUBTYPELIST: "SUBTYPE LIST",
    NEWSUBTYPE: "NEW SUBTYPE",
    ARE_YOU_SURE_TAKE_ACTION_REQUEST: "Please confirm this action -",
    CREATE: "CREATE",
    CREATE_REQUEST: "CREATE REQUEST",
    REACHME_VOLUNTEERS_LIST: "VOLUNTEERS LIST",
    REACHME_VOLUNTEERS_DETAILS: "VOLUNTEERS DETAILS",
    AREA: "Area",
    SERVING_AREA: "Serving Area",
    REQUEST_TYPE: "Request type",
    APPROVE: "Approve",
    REJECT: "Reject",
    BLOCK: "Block",
    UNBLOCK: "Unblock",
    FORWARD_TO: "FORWARD TO",
    FORWARD_CONFIRMATION: "Are you sure you want to forward this request",
    APPROVED_DATE: "Approved date",
    BLOCKED_REASON: "Blocked reason",
    VOLUNTEERS_LIST: "VOLUNTEERS LIST",
    NO_FEEDBACKS: "No feedback",
    APPLY: "APPLY",
    CLEAR: "CLEAR",
    PROVIDE_FEEDBACK: "Please provide feedback type",
    PROVIDE_TITLE: "Please provide title",
    PROVIDE_DESCRIPTION: "Please provide description",
    FEEDBACK_SENT_SUCCESS: "feedback sent successfully",
    COULDNOT_FEEDBACK_SENT: "Couldn't sent feedack",
    TAKE_ACTION_SUCCESS: "Action taken successfully",
    TAKE_ACTION_FAIL: "Couldn't take action",
    NO_LOCATIONS: "No locations",
    LOCATION_ADDED_SUCCESS: "Location Added sucessfully",
    LOCATION_ADDED_FAIL: "Coundn't add location",
    PROVIDE_NAME: "Please provide name",
    PROVIDE_ADDRESS: "Please provide address",
    PROVIDE_LOCATION_TYPE: "Please provide location type",
    ACTIVATE_SUCCESS: "Activated successfully",
    ACTIVATE_FAIL: "Couldn't activate",
    CHECK_IN_HISTORY: "Check-in History",
    NO_CHECK_IN: "No check-ins",
    SELECT_LOCATION: "Select Location",
    SELECT_PERSON: "Select Person",
    VIEW_ALL_CHECKINS: "View all Check-in",
    VIEW_BY_PERSON: "View by Person",
    VIEW_BY_LOCATION: "View by Location",
    NO_DEPARTMENTS: "NO DEPARTMENTS AVAILABLE",
    NO_REQUEST: "NO REQUEST",
    NO_PERSON: "NO PERSON",
    PROVIDE_AGE: "Please provide age",
    PROVIDE_GENDER: "Please provide gender",
    PERSON_CREATE_SUCCESS: "Person created successfully",
    PERSON_CREATE_FAIL: "Couldn't create person",
    SELECT_REQUEST_TYPE: "Please select Request type",
    SELECT_AREA: "Please select area",
    REQUEST_CREATE_SUCCESS: "Request created successfully",
    REQUEST_CREATE_FAIL: "Couldn't create request",
    ACTION_TAKEN_SUCCESS: "Action taken successfully",
    ACTION_TAKEN_FAIL: "Couldn't take action",
    REMOVE_SUCCESS: "Removed Successfully",
    REMOVE_FAIL: "Couldn't remove",
    FORWARD_SUCCESS: "Forwarded successfully",
    OFFICER_ASSIGN_SUCCESS: "Officer assigned successfully",
    COULDNOT_FORWARD: "Couldn't forward",
    COULDNOTASSIGN: "Couldn't assign officer",
    NO_OFFICIALS: "No Official",
    CHECKIN_SUCCESS: "Checkedin successfully",
    CHECKIN_FAIL: "Couldn't checkedin",
    REMARKS_ADDED_SUCCES: "Remarks added successfully",
    REMARKS_ADDED_FAIL: "Couldn't add remarks",
    ADD_REMARKS: "ADD REMARKS",
    NO_REMARKS_LOG: "No Remarks log",
    PLEASE_PROVIDE_TITLE: "Please provide Title",
    PLEASE_PROVIDE_DEPARTMENT: "Please select Department",
    SUBTYPE_CREATE_SUCCESS: "Subtype created successfully",
    SUBTYPE_CREATE_FAIL: "Couldn't create subtype",
    APPROVED_SUCCESS: "Approved successfully",
    APPROVED_FAIL: "Couldn't approve",
    UNBLOCKED_SUCCESS: "Unblocked successfully",
    UNBLOCKED_FAIL: "Couldn't unblock",
    BLOCKED_SUCCESS: "Blocked successfully",
    BLOCKED_FAIL: "Couldn't block",
    UPDATE_PERSON: "UPDATE PERSON",
    UPDATE: "UPDATE",
    PERSON_UPDATE_SUCCESS: "Person updated successfully",
    PERSON_UPDATE_FAIL: "Couldn't update person",
    PERSON_REJECT_SUCCESS: "Person rejected successfully",
    PERSON_REJECT_FAIL: "Couldn't reject person",
    PENDING: "PENDING",
    ACTIVE: "ACTIVE",
    BLOCKED: "BLOCKED",
    SUBTYPE: "Sub Type",
    PERSON: "Person",
    REQUIREDCOUNT: "Required Count",
    CONTACTPERSON: "Contact Person",
    CONTACTNUMBER: "Contact Number",
    WHEN: "When",
    NO_OFFICERS: "No Officers",
    NO_OPEN_REQUESTS: "No open request available right now!!!",
    NO_COMPLETED_REQUESTS: "No completed request available right now!!!",
    OPEN: "OPEN",
    COMPLETED: "COMPLETED",
    NO_VOLUNTEERS: "No volunteers available right now!!!",
    ID_PROOF: "ID Proof",
    ADDRESS_PROOF: "Address Proof",
    NO_HISTORY: "No history available right now!!!",
    NO_PERSONS: "No Persons",
    ASSIGN_OFFICER: "Assign officer",
    MALE: "Male",
    FEMALE: "Female",
    TRANSGENDER: "Transgender",
    NO_SUBTYPES: "No Subtypes",
    NO_PENDING_VOLUNTEERS: "No pending volunteers available right now!!!",
    NO_ACTIVE_VOLUNTEERS: "No active volunteers available right now!!!",
    NO_BLOCKED_VOLUNTEERS: "No blocked volunteers available right now!!!!",
    SELECT_REQUESTTYPE: "Select request type",
    SELECT_SUB_REQUESTTYPE: "Select request sub type",
    CREATED_ON: "Created on",
    INVALID_QR: "Invalid QR",
    PEOPLE_DIRECTORY: "PEOPLE DIRECTORY",
    PEOPLE: "PERSON",
    NO_PEOPLE: "NO PEOPLE",
    NO_CHECKINS: "No Checkins",
    ABOUT: "ABOUT",
    CHECKIN_LABEL: "Check-in",
    TAKE_SELFIE: "Take Selfie",
    UN_VERIFIED: "Your profile is unverified. Please contact your reporting officer",
    VERIFIED: "Verified",
    VERIFY_ALERT: "Are you sure you want to verify",
    REMOVE_ALERT: "Are you sure you want to remove",
    PLEASE_TAKE_SELFIE: "Please take selfie",
    POLICE_OFFICER_DIRECTORY: "POLICE DIRECTORY",
    OFFICER_VERIFIED_SUCCESSFULLY: "Officer verified successfully",
    COULD_NOT_VERIFY: "Couldn't verified",
    OFFICER_REMOVED_SUCCESSFULLY: "Officer removed successfully",
    COULD_NOT_REMOVE: "Couldn't remove",
    SELECT_OFFICE: "Please select your office",
    ENTER_VALID_MOBILE: "Please enter Valid mobile number",
    POLICE_OFFICERS: "Police Officers",
    SHOW_ALL_OFFICERS: "Show all officers",
    DELETE_ALERT: "Are you sure you want to delete",
    OFFICER_DELETED_SUCCESSFULLY: "Officer deleted successfully",
    COULD_NOT_DELETE: "Couldn't delete",
    PROFILE_HEADER: "PROFILE",
    UPDATE: "Update",
    MOBILE_CANT_EDIT: "This mobile number cannot be changed",
};

export const TA = {
    SETTINGS: "அமைப்புகள்",
    HOME: "முகப்பு",
    FEEDBACK: "கருத்து",
    FEEDBACKS: "கருத்துகள்",
    REACHME: "ரீச்மீ",
    LANGUAGE: "மொழி",
    TITLE: "தலைப்பு",
    DISCRIPTION: "விளக்கம்",
    PHOTO: "புகைப்படம்",
    SEND: "அனுப்பு",
    EBEAT: "இ-பீட்",
    SCAN: "ஸ்கேன்",
    SCAN_QR_CODE: "QR குறியீட்டை ஸ்கேன் செய்யுங்கள்",
    DETAILS: "விவரங்கள்",
    CHECKIN: "சரிபார்ப்பு",
    ACTIVATE: "செயல்படுத்து",
    PROFILE: "சுயவிவரம்",
    LOGOUT: "வெளியேறு",
    REQUESTDETAILS: "கோரிக்கை விவரங்கள்",
    REQUESTNO: "கோரிக்கை எண்",
    TIME: "நேரம்",
    REQUESTOR: "கோருபவர்",
    REQUIREMENT: "தேவை",
    STATUS: "நிலை",
    VOLUNTEERSCOUNT: "தொண்டர்கள் எண்ணிக்கை",
    VOLUNTEERS: "தொண்டர்கள்",
    VIEW: "காண்க",
    REQUEST_TAKEN_VOLUNTEEERS: "தொண்டர்கள்",
    ADD_REQUEST: "கோரிக்கையைச் சேர்",
    TEQUEST_TYPE: "கோரிக்கை வகை",
    ADD: "சேர்",
    CANCEL: "ரத்துசெய்",
    DATE: "தேதி",
    OK: "சரி",
    WANT_TO_LOGOUT: "நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா?",
    FEEDBACK_TYPE: "கருத்து வகை",
    LOCATION_NOT_ACTIVATED: "இந்த இடம் இன்னும் செயல்படுத்தப்படவில்லை",
    YOU_ARE_IN_LOCATION: "நீங்கள் இருப்பிடத்தில் இருக்கிறீர்கள்",
    YOU_ARE: "நீங்கள் இருப்பிடத்திலிருந்து",
    AWAY_FROM_LOCATION: "மீட்டர் தொலைவில் இருக்கிறீர்கள்",
    SEND_FEEDBACK_TO: "கருத்தினை அனுப்ப",
    FEEDBACK_TYPES: "கருத்து வகைகள்",
    TAKE_ACTIONS: "நடவடிக்கை எடு",
    ACTIONS: "நடவடிக்கைகள்",
    CONFIRMATION: "உறுதிப்படுத்தல்",
    ARE_YOU_SURE_TAKE_ACTION: "இந்த கருத்து மீது நடவடிக்கை எடுக்க விரும்புகிறீர்களா?",
    SEND_FEEDBACK_TO_OFFICE: "இந்த கருத்தை நீங்கள் அனுப்ப விரும்புகிறீர்களா?",
    SELECT: "தேர்ந்தெடு",
    TYPE_HERE: "இங்கே தட்டச்சு செய்க",
    OFFICE: "க்கு",
    LANGUAGES: "மொழிகள்",
    WELFAREREQUEST: "நல்வாழ்வு கோரிக்கை",
    PERSONLIST: "நபர் பட்டியல்",
    CREATE: "சேர்",
    OFFICER_DIRECTORY: "அதிகாரிகள் கையேடு",
    REMARKS: "கருத்துரைகள்",
    NAME: "பெயர்",
    AGE: "வயது",
    GENDER: "பாலினம்",
    CONTACTNUMBER1: "தொடர்பு எண் 1",
    CONTACTNUMBER2: "தொடர்பு எண் 2",
    ADDRESS: "முகவரி",
    REQUESTTYPE: "கோரிக்கை வகை",
    // OFFICER_DIRECTORY: "அதிகாரிகள் கையேடு",
    // CREATE: "Create",
    REQUEST_DETAILS: "கோரிக்கை விவரங்கள்",
    ASSIGNED_TO: "உரிமை மாற்றம் பெற்றவர்",
    ASSIGN_TO: "உரிமை மாற்றம்",
    ASSIGNED_DATE: "ஒதுக்கப்பட்ட தேதி",
    FORWARD: "அனுப்பு",
    REMOVE: "அகற்று",
    HISTORY: "வரலாறு",
    TAKE_ACTIONS_LABEL: "நடவடிக்கை எடு",
    ACTION_LOG: "நடவடிக்கைகள் பதிவு",
    REMARKS_LOG: "குறிப்புகள் பதிவு",
    OFFICERS: "அதிகாரிகள்",
    OFFICER: "அதிகாரி",
    LOCATION_LABLE: "இடம்",
    LOCATIONS: "இடங்கள்",
    LOCATION: "இடம்",
    ADD_LOCATION: "இடத்தைச் சேர்",
    // NAME: "பெயர்",
    // ADDRESS: "முகவரி",
    LOCATION_TYPE: "இருப்பிட வகை",
    ACTIVATED_ON: "செயல்படுத்தப்பட்டது",
    QR_CODE: "க்யு ஆர் குறியீடு",
    DOWNLOAD: "பதிவிறக்க",
    CHECKIN_HISTORY: "சரிபார்ப்பு வரலாறு",
    DEPARTMENT: "துறை",
    CREATESUBTYPE: "துணை வகையை சேர்க்க",
    DESCRIPTION: "விளக்கம்",
    CREATEPERSON: "புதிய நபர் சேர்க்க",
    SUBTYPELIST: "துணைவகை பட்டியல்",
    NEWSUBTYPE: "புதிய துணைவகை",
    ARE_YOU_SURE_TAKE_ACTION_REQUEST: "தயவுசெய்து இந்த செயலை உறுதிப்படுத்தவும்",
    CREATE_REQUEST: "கோரிக்கை சேர்க்க",
    REACHME_VOLUNTEERS_LIST: "வாலண்டியர்ஸ் பட்டியல்",
    REACHME_VOLUNTEERS_DETAILS: "வாலண்டியர் விவரங்கள்",
    AREA: "பகுதி",
    SERVING_AREA: "சேவை செய்யும் பகுதி",
    REQUEST_TYPE: "கோரிக்கை வகை",
    APPROVE: "ஒப்புதல்",
    REJECT: "நிராகரிக்க",
    BLOCK: "தடு",
    UNBLOCK: "தடைநீக்கு",
    FORWARD_TO: "உரிமை மாற்றம்",
    FORWARD_CONFIRMATION: "இந்த கோரிக்கையை நீங்கள் அனுப்ப விரும்புகிறீர்களா?",
    APPROVED_DATE: "அங்கீகரிக்கப்பட்ட தேதி",
    BLOCKED_REASON: "தடுக்கப்பட்ட காரணம்",
    VOLUNTEERS_LIST: "வாலண்டியர்ஸ் லிஸ்ட்",
    NO_FEEDBACKS: "கருத்துகள் இல்லை",
    FILTERS: "வடிகட்டிகள்",
    APPLY: "விண்ணப்பி",
    CLEAR: "அழி",
    PROVIDE_FEEDBACK: "தயவுசெய்து கருத்து வகையை வழங்கவும்",
    PROVIDE_TITLE: "தயவுசெய்து தலைப்பை வழங்கவும்",
    PROVIDE_DESCRIPTION: "தயவு செய்து விளக்கம் தாருங்கள்",
    FEEDBACK_SENT_SUCCESS: "கருத்து வெற்றிகரமாக அனுப்பப்பட்டது",
    COULDNOT_FEEDBACK_SENT: "கருத்து அனுப்ப முடியவில்லை",
    TAKE_ACTION_SUCCESS: "நடவடிக்கை வெற்றிகரமாக எடுக்கப்பட்டது",
    TAKE_ACTION_FAIL: "நடவடிக்கை எடுக்க முடியவில்லை",
    NO_LOCATIONS: "இடங்கள் இல்லை",
    LOCATION_ADDED_SUCCESS: "இடம் வெற்றிகரமாகச் சேர்க்கப்பட்டது",
    LOCATION_ADDED_FAIL: "இருப்பிடத்தைச் சேர்க்க முடியவில்லை",
    PROVIDE_NAME: "தயவுசெய்து பெயரை வழங்கவும்",
    PROVIDE_ADDRESS: "தயவுசெய்து முகவரியை வழங்கவும்",
    PROVIDE_LOCATION_TYPE: "தயவுசெய்து இருப்பிட வகையை வழங்கவும்",
    ACTIVATE_SUCCESS: "வெற்றிகரமாக செயல்படுத்தப்பட்டது",
    ACTIVATE_FAIL: "செயல்படுத்த முடியவில்லை",
    CHECK_IN_HISTORY: "சரிபார்ப்பு வரலாறு",
    NO_CHECK_IN: "செக்-இன் இல்லை",
    SELECT_LOCATION: "இருப்பிடத்தைத் தேர்ந்தெடு",
    SELECT_PERSON: "நபரைத் தேர்ந்தெடுக்கவும்",
    VIEW_ALL_CHECKINS: "அனைத்து செக்-இன் பார்க்கவும்",
    VIEW_BY_PERSON: "நபரால் பார்க்கவும்",
    VIEW_BY_LOCATION: "இருப்பிடம் மூலம் பார்க்கவும்",
    NO_DEPARTMENTS: "துறைகள் இல்லை",
    NO_REQUEST: "கோரிக்கை இல்லை",
    NO_PERSON: "இல்லை நபர்",
    PROVIDE_AGE: "தயவுசெய்து வயதை வழங்கவும்",
    PROVIDE_GENDER: "பாலினத்தை வழங்கவும்",
    PERSON_CREATE_SUCCESS: "வெற்றிகரமாக உருவாக்கப்பட்ட நபர்",
    PERSON_CREATE_FAIL: "நபரை உருவாக்க முடியவில்லை",
    SELECT_REQUEST_TYPE: "கோரிக்கை வகையைத் தேர்ந்தெடுக்கவும்",
    SELECT_AREA: "தயவுசெய்து பகுதியைத் தேர்ந்தெடுக்கவும்",
    REQUEST_CREATE_SUCCESS: "கோரிக்கை வெற்றிகரமாக உருவாக்கப்பட்டது",
    REQUEST_CREATE_FAIL: "கோரிக்கையை உருவாக்க முடியவில்லை",
    ACTION_TAKEN_SUCCESS: "நடவடிக்கை வெற்றிகரமாக எடுக்கப்பட்டது",
    ACTION_TAKEN_FAIL: "நடவடிக்கை எடுக்க முடியவில்லை",
    REMOVE_SUCCESS: "வெற்றிகரமாக அகற்றப்பட்டது",
    REMOVE_FAIL: "அகற்ற முடியவில்லை",
    FORWARD_SUCCESS: "வெற்றிகரமாக அனுப்பப்பட்டது",
    OFFICER_ASSIGN_SUCCESS: "அதிகாரி வெற்றிகரமாக நியமிக்கப்பட்டார்",
    COULDNOT_FORWARD: "முன்னெடுக்க முடியவில்லை",
    COULDNOTASSIGN: "அதிகாரியை நியமிக்க முடியவில்லை",
    NO_OFFICIALS: "அதிகாரப்பூர்வமில்லை",
    CHECKIN_SUCCESS: "வெற்றிகரமாக சரிபார்க்கப்பட்டது",
    CHECKIN_FAIL: "சரிபார்க்க முடியவில்லை",
    REMARKS_ADDED_SUCCES: "குறிப்புகள் வெற்றிகரமாக சேர்க்கப்பட்டன",
    REMARKS_ADDED_FAIL: "குறிப்புகளைச் சேர்க்க முடியவில்லை",
    ADD_REMARKS: "குறிப்புகளைச் சேர்க்கவும்",
    NO_REMARKS_LOG: "குறிப்புகள் பதிவு இல்லை",
    PLEASE_PROVIDE_TITLE: "தயவுசெய்து தலைப்பை வழங்கவும்",
    PLEASE_PROVIDE_DEPARTMENT: "தயவுசெய்து துறையைத் தேர்ந்தெடுக்கவும்",
    SUBTYPE_CREATE_SUCCESS: "துணை வகை வெற்றிகரமாக உருவாக்கப்பட்டது",
    SUBTYPE_CREATE_FAIL: "துணை வகையை உருவாக்க முடியவில்லை",
    APPROVED_SUCCESS: "வெற்றிகரமாக அங்கீகரிக்கப்பட்டது",
    APPROVED_FAIL: "ஒப்புக்கொள்ள முடியவில்லை",
    UNBLOCKED_SUCCESS: "வெற்றிகரமாகத் திறக்கப்பட்டது",
    UNBLOCKED_FAIL: "தடைநீக்க முடியவில்லை",
    BLOCKED_SUCCESS: "வெற்றிகரமாக தடுக்கப்பட்டது",
    BLOCKED_FAIL: "தடுக்க முடியவில்லை",
    UPDATE_PERSON: "நபரைப் புதுப்பிக்கவும்",
    UPDATE: "புதுப்பிக்க",
    PERSON_UPDATE_SUCCESS: "நபர் புதுப்பிக்கப்பட்டார்",
    PERSON_UPDATE_FAIL: "நபரைப் புதுப்பிக்க முடியவில்லை",
    PERSON_REJECT_SUCCESS: "நபர் நிராகரிக்கப்பட்டார்",
    PERSON_REJECT_FAIL: "நபரை நிராகரிக்க முடியவில்லை",
    PENDING: "நிலுவை",
    ACTIVE: "செயலில்",
    BLOCKED: "தடுக்கப்பட்டது",
    SUBTYPE: "துணை வகை",
    PERSON: "நபர்",
    REQUIREDCOUNT: "தேவையான எண்ணிக்கை",
    CONTACTPERSON: "தொடர்பு நபர்",
    CONTACTNUMBER: "தொடர்பு எண்",
    WHEN: "எப்பொழுது",
    NO_OFFICERS: "அதிகாரிகள் இல்லை",
    NO_OPEN_REQUESTS: "இப்போது திறந்த கோரிக்கை இல்லை!!!",
    NO_COMPLETED_REQUESTS: "முழுமையான கோரிக்கை எதுவும் இப்போது இல்லை!!!",
    OPEN: "திற",
    COMPLETED: "நிறைவு",
    NO_VOLUNTEERS: "இப்போது தன்னார்வலர்கள் இல்லை !!!",
    ID_PROOF: "அடையாள சான்று",
    ADDRESS_PROOF: "முகவரி சான்று",
    NO_HISTORY: "இப்போது வரலாறு கிடைக்கவில்லை!!!",
    NO_PERSONS: "நபர்கள் இல்லை",
    ASSIGN_OFFICER: "அதிகாரியை நியமிக்கவும்",
    ASSIGN_CONFIRMATION: "நீங்கள் இந்த அதிகாரியை நியமிக்க விரும்புகிறீர்களா?",
    MALE: "ஆண்",
    FEMALE: "பெண்",
    TRANSGENDER: "திருநங்கை",
    NO_SUBTYPES: "துணை வகைகள் இல்லை",
    NO_PENDING_VOLUNTEERS: "நிலுவையில் உள்ள தன்னார்வலர்கள் இப்போது இல்லை!!!",
    NO_ACTIVE_VOLUNTEERS: "செயலில் உள்ள தன்னார்வலர்கள் இப்போது இல்லை!!!",
    NO_BLOCKED_VOLUNTEERS: "தடுக்கப்பட்ட தன்னார்வலர்கள் இப்போது இல்லை!!!!",
    SELECT_REQUESTTYPE: "கோரிக்கை வகையைத் தேர்ந்தெடுக்கவும்",
    SELECT_SUB_REQUESTTYPE: "கோரிக்கை துணை வகையைத் தேர்ந்தெடுக்கவும்",
    CREATED_ON: "உருவாக்கப்பட்ட தேதி",
    INVALID_QR: "தவறான க்யு ஆர்",
    PEOPLE_DIRECTORY: "மக்கள் டைரக்டரி",
    PEOPLE: "நபர்",
    NO_PEOPLE: "மக்கள் இல்லை",
    NO_CHECKINS: "செக்கின்கள் இல்லை",
    ABOUT: "பற்றி",
    CHECKIN_LABEL: "செக் இன்",
    TAKE_SELFIE: "செல்ஃபி எடு",
    UN_VERIFIED:
        "உங்கள் சுயவிவரம் சரிபார்க்கப்படவில்லை. தயவுசெய்து உங்கள் அறிக்கை அதிகாரியை தொடர்பு கொள்ளவும்",
    VERIFIED: "சரிபார்க்கப்பட்டது",
    VERIFY_ALERT: "நீங்கள் சரிபார்க்க விரும்புகிறீர்களா",
    REMOVE_ALERT: "நீங்கள் நீக்க விரும்புகிறீர்களா",
    PLEASE_TAKE_SELFIE: "தயவுசெய்து செல்ஃபி எடுங்கள்",
    POLICE_OFFICER_DIRECTORY: "போலீஸ் டைரக்டரி",
    OFFICER_VERIFIED_SUCCESSFULLY: "அதிகாரி சரிபார்க்கப்பட்டார்",
    COULD_NOT_VERIFY: "சரிபார்க்க முடியவில்லை",
    OFFICER_REMOVED_SUCCESSFULLY: "அதிகாரி அகற்றப்பட்டார்",
    COULD_NOT_REMOVE: "அகற்ற முடியவில்லை",
    SELECT_OFFICE: "தயவுசெய்து உங்கள் அலுவலகத்தைத் தேர்ந்தெடுக்கவும்",
    ENTER_VALID_MOBILE: "செல்லுபடியாகும் மொபைல் எண்ணை உள்ளிடவும்",
    POLICE_OFFICERS: "போலீஸ் அதிகாரிகள்",
    SHOW_ALL_OFFICERS: "அனைத்து அதிகாரிகளையும் காட்டு",
    DELETE_ALERT: "நீங்கள் நீக்க விரும்புகிறீர்களா?",
    OFFICER_DELETED_SUCCESSFULLY: "அதிகாரி நீக்கப்பட்டார்",
    COULD_NOT_DELETE: "நீக்க முடியவில்லை",
    PROFILE_HEADER: "சுயவிவரம்",
    UPDATE: "புதுப்பி",
    MOBILE_CANT_EDIT: "இந்த மொபைல் எண்ணைத் திருத்த முடியாது",
};
